modules/DoubleEntry/Http/routes.php
<?php

Route::group([
    'middleware' => 'admin',
    'prefix' => 'double-entry',
    'namespace' => 'Modules\DoubleEntry\Http\Controllers'
], function () {
    Route::get('chart-of-accounts/{chart_of_account}/enable', 'ChartOfAccounts@enable')->name('chart-of-accounts.enable');
    Route::get('chart-of-accounts/{chart_of_account}/disable', 'ChartOfAccounts@disable')->name('chart-of-accounts.disable');
    Route::resource('chart-of-accounts', 'ChartOfAccounts');

    Route::get('journal-entry/addItem', 'JournalEntry@addItem')->middleware(['double-entry-money'])->name('journal-entry.add.item');
    Route::post('journal-entry/totalItem', 'JournalEntry@totalItem')->middleware(['double-entry-money'])->name('journal-entry.total.item');
    Route::resource('journal-entry', 'JournalEntry', ['middleware' => ['double-entry-money']]);

    Route::get('general-ledger/export', 'GeneralLedger@export')->name('general-ledger.export');
    Route::resource('general-ledger', 'GeneralLedger');
    Route::get('balance-sheet/export', 'BalanceSheet@export')->name('balance-sheet.export');
    Route::resource('balance-sheet', 'BalanceSheet');
    Route::get('trial-balance/export', 'TrialBalance@export')->name('trial-balance.export');
    Route::resource('trial-balance', 'TrialBalance');
});

modules/DoubleEntry/Http/Controllers/GeneralLedger.php
<?php

namespace Modules\DoubleEntry\Http\Controllers;

use App\Http\Controllers\Controller;
use Date;
use Modules\DoubleEntry\Models\Account;
use Modules\DoubleEntry\Models\DEClass;
use Modules\DoubleEntry\Models\Ledger;

class GeneralLedger extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        list($ledgers) = $this->getData();

        // Check if it's a print or normal request
        if (request('print')) {
            $template = 'print';
        } else {
            $template = 'index';
        }

        return view('double-entry::general-ledger.' . $template, compact('ledgers'));
    }

    public function export()
    {
        \Excel::create(trans('double-entry::general.general_ledger'), function($excel) {
            $excel->sheet(trans('double-entry::general.general_ledger'), function($sheet) {
                $template = 'body';

                list($ledgers) = $this->getData();

                $sheet->loadView('double-entry::general-ledger.' . $template, compact('ledgers'));
            });
        })->download('xlsx');
    }

    protected function getData()
    {
        // Get year
        $year = request('year', Date::now()->year);

        $limit = request('limit', setting('general.list_limit', '25'));

        $ledgers = Ledger::with(['account'])->orderBy('issued_at', 'desc')->paginate($limit);

        return [$ledgers];
    }
}

modules/DoubleEntry/Resources/views/general-ledger/body.blade.php
<div class="box-body">
    <div class="table table-responsive">
        <table class="table table-striped table-hover" id="tbl-taxes">
            <thead>
                <tr>
                    <th class="col-md-2">{{ trans('general.date') }}</th>
                    <th class="col-md-4">{{ trans_choice('general.accounts', 1) }}</th>
                    <th class="col-md-2 text-right amount-space">{{ trans('general.amount') }}</th>
                </tr>
            </thead>
            <tbody>
            @foreach($ledgers as $item)
                <tr>
                    <td>{{ Date::parse($item->issued_at)->format($date_format) }}</td>
                    <td>{{ trans($item->account->name) }}</td>
                    @if ($item->debit)
                    <td class="text-right amount-space">@money($item->debit, setting('general.default_currency'), true)</td>
                    @else
                    <td class="text-right amount-space">@money($item->credit, setting('general.default_currency'), true)</td>
                    @endif
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
<!-- /.box-body -->

modules/DoubleEntry/Resources/views/general-ledger/index.blade.php
@extends('layouts.admin')

@section('title', trans('double-entry::general.general_ledger'))

@section('new_button')
    <span class="new-button"><a href="{{ route('general-ledger.index') }}?print=1&year={{ request('year', $this_year) }}" target="_blank" class="btn btn-default btn-sm"><span class="fa fa-print"></span> &nbsp;{{ trans('general.print') }}</a></span> <span><a href="{{ route('general-ledger.export') }}?print=1&year={{ request('year', $this_year) }}" class="btn btn-default btn-sm"><span class="fa fa-file-excel-o"></span> &nbsp;{{ trans('general.export') }}</a></span>
@endsection

@section('content')<!-- Default box -->
    <div class="box box-success">
        @include('double-entry::general-ledger.body')

        <div class="box-footer">
            @include('partials.admin.pagination', ['items' => $ledgers, 'type' => 'transactions'])
        </div>
        <!-- /.box-footer -->
    </div>
    <!-- /.box -->
@endsection

modules/DoubleEntry/Resources/views/general-ledger/print.blade.php
@extends('layouts.print')

@section('title', trans('double-entry::general.general_ledger'))

@section('content')
    <div class="box-header">
        <h2>{{ trans('double-entry::general.general_ledger') }}</h2>
        <div class="text-muted">
            {{ setting('general.company_name') }}
            <br/>
            {{ Date::parse(request('year') . '-1-1')->format($date_format) }} - {{ Date::parse(request('year') . '-12-31')->format($date_format) }}
        </div>
    </div>
    @include('double-entry::general-ledger.body')
@endsection